import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"

// ** styles
import "../styles/globals.scss";
import '@smastrom/react-rating/style.css'

// ** Libs
import { cn } from "@/lib/utils"

// ** Store
import Providers from "./providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "LenderSqr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body   
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}>
            {children}
        </body>
      </html>
    </Providers>
  );
}
